defaultBaseImage: cgr.dev/chainguard/static@sha256:ea695a20a7bfb81bdc4acb2cf94588eb1e85d29fcd699cce1f8cee8fbeb4ce8a
baseImageOverrides:
  # Use the combined base image for images that should include Windows support.
  # The :latest tag is automatically replaced with the actual digest during releases by tekton/publish.yaml.
  github.com/tektoncd/pipeline/cmd/entrypoint: ghcr.io/tektoncd/pipeline/github.com/tektoncd/pipeline/combined-base-image:latest
  github.com/tektoncd/pipeline/cmd/nop: ghcr.io/tektoncd/pipeline/github.com/tektoncd/pipeline/combined-base-image:latest
  github.com/tektoncd/pipeline/cmd/workingdirinit: ghcr.io/tektoncd/pipeline/github.com/tektoncd/pipeline/combined-base-image:latest
  github.com/tektoncd/pipeline/cmd/resolvers: ghcr.io/tektoncd/plumbing/tini-git@sha256:2c18f0b3ed4394e27068b5c70bb55419797e8fc743d8ea9e0c2766001b36b5b4
