apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: object-param-result-
spec:
  params:
    - name: gitrepo
      value:
        url: "xyz.com"
        commit: "sha123"
  taskSpec:
    steps:
      - name: echo-object-params
        image: mirror.gcr.io/bash@sha256:e320b40b14abc61f053286705070342c46034a549a276b798e64541457c4af92
        args: [
          "echo",
          "--url=$(params.gitrepo.url)",
          "--commit=$(params.gitrepo.commit)",
        ]
