/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	v1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1"
	scheme "github.com/tektoncd/pipeline/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PipelinesGetter has a method to return a PipelineInterface.
// A group's client should implement this interface.
type PipelinesGetter interface {
	Pipelines(namespace string) PipelineInterface
}

// PipelineInterface has methods to work with Pipeline resources.
type PipelineInterface interface {
	Create(ctx context.Context, pipeline *v1.Pipeline, opts metav1.CreateOptions) (*v1.Pipeline, error)
	Update(ctx context.Context, pipeline *v1.Pipeline, opts metav1.UpdateOptions) (*v1.Pipeline, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Pipeline, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.PipelineList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Pipeline, err error)
	PipelineExpansion
}

// pipelines implements PipelineInterface
type pipelines struct {
	*gentype.ClientWithList[*v1.Pipeline, *v1.PipelineList]
}

// newPipelines returns a Pipelines
func newPipelines(c *TektonV1Client, namespace string) *pipelines {
	return &pipelines{
		gentype.NewClientWithList[*v1.Pipeline, *v1.PipelineList](
			"pipelines",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1.Pipeline { return &v1.Pipeline{} },
			func() *v1.PipelineList { return &v1.PipelineList{} }),
	}
}
