/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	v1 "github.com/tektoncd/pipeline/pkg/apis/pipeline/v1"
	scheme "github.com/tektoncd/pipeline/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// TasksGetter has a method to return a TaskInterface.
// A group's client should implement this interface.
type TasksGetter interface {
	Tasks(namespace string) TaskInterface
}

// TaskInterface has methods to work with Task resources.
type TaskInterface interface {
	Create(ctx context.Context, task *v1.Task, opts metav1.CreateOptions) (*v1.Task, error)
	Update(ctx context.Context, task *v1.Task, opts metav1.UpdateOptions) (*v1.Task, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Task, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.TaskList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Task, err error)
	TaskExpansion
}

// tasks implements TaskInterface
type tasks struct {
	*gentype.ClientWithList[*v1.Task, *v1.TaskList]
}

// newTasks returns a Tasks
func newTasks(c *TektonV1Client, namespace string) *tasks {
	return &tasks{
		gentype.NewClientWithList[*v1.Task, *v1.TaskList](
			"tasks",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1.Task { return &v1.Task{} },
			func() *v1.TaskList { return &v1.TaskList{} }),
	}
}
