//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2020 The Tekton Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	pipeline "github.com/tektoncd/pipeline/pkg/apis/pipeline"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Param)(nil), (*pipeline.Param)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Param_To_pipeline_Param(a.(*Param), b.(*pipeline.Param), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*pipeline.Param)(nil), (*Param)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_pipeline_Param_To_v1_Param(a.(*pipeline.Param), b.(*Param), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ParamSpec)(nil), (*pipeline.ParamSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ParamSpec_To_pipeline_ParamSpec(a.(*ParamSpec), b.(*pipeline.ParamSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*pipeline.ParamSpec)(nil), (*ParamSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_pipeline_ParamSpec_To_v1_ParamSpec(a.(*pipeline.ParamSpec), b.(*ParamSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ParamValue)(nil), (*pipeline.ParamValue)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ParamValue_To_pipeline_ParamValue(a.(*ParamValue), b.(*pipeline.ParamValue), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*pipeline.ParamValue)(nil), (*ParamValue)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_pipeline_ParamValue_To_v1_ParamValue(a.(*pipeline.ParamValue), b.(*ParamValue), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PipelineWorkspaceDeclaration)(nil), (*pipeline.PipelineWorkspaceDeclaration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_PipelineWorkspaceDeclaration_To_pipeline_PipelineWorkspaceDeclaration(a.(*PipelineWorkspaceDeclaration), b.(*pipeline.PipelineWorkspaceDeclaration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*pipeline.PipelineWorkspaceDeclaration)(nil), (*PipelineWorkspaceDeclaration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_pipeline_PipelineWorkspaceDeclaration_To_v1_PipelineWorkspaceDeclaration(a.(*pipeline.PipelineWorkspaceDeclaration), b.(*PipelineWorkspaceDeclaration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PropertySpec)(nil), (*pipeline.PropertySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_PropertySpec_To_pipeline_PropertySpec(a.(*PropertySpec), b.(*pipeline.PropertySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*pipeline.PropertySpec)(nil), (*PropertySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_pipeline_PropertySpec_To_v1_PropertySpec(a.(*pipeline.PropertySpec), b.(*PropertySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Sidecar)(nil), (*pipeline.Sidecar)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Sidecar_To_pipeline_Sidecar(a.(*Sidecar), b.(*pipeline.Sidecar), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*pipeline.Sidecar)(nil), (*Sidecar)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_pipeline_Sidecar_To_v1_Sidecar(a.(*pipeline.Sidecar), b.(*Sidecar), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Step)(nil), (*pipeline.Step)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Step_To_pipeline_Step(a.(*Step), b.(*pipeline.Step), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*pipeline.Step)(nil), (*Step)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_pipeline_Step_To_v1_Step(a.(*pipeline.Step), b.(*Step), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StepOutputConfig)(nil), (*pipeline.StepOutputConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_StepOutputConfig_To_pipeline_StepOutputConfig(a.(*StepOutputConfig), b.(*pipeline.StepOutputConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*pipeline.StepOutputConfig)(nil), (*StepOutputConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_pipeline_StepOutputConfig_To_v1_StepOutputConfig(a.(*pipeline.StepOutputConfig), b.(*StepOutputConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StepTemplate)(nil), (*pipeline.StepTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_StepTemplate_To_pipeline_StepTemplate(a.(*StepTemplate), b.(*pipeline.StepTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*pipeline.StepTemplate)(nil), (*StepTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_pipeline_StepTemplate_To_v1_StepTemplate(a.(*pipeline.StepTemplate), b.(*StepTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Task)(nil), (*pipeline.Task)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Task_To_pipeline_Task(a.(*Task), b.(*pipeline.Task), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*pipeline.Task)(nil), (*Task)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_pipeline_Task_To_v1_Task(a.(*pipeline.Task), b.(*Task), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TaskList)(nil), (*pipeline.TaskList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_TaskList_To_pipeline_TaskList(a.(*TaskList), b.(*pipeline.TaskList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*pipeline.TaskList)(nil), (*TaskList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_pipeline_TaskList_To_v1_TaskList(a.(*pipeline.TaskList), b.(*TaskList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TaskResult)(nil), (*pipeline.TaskResult)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_TaskResult_To_pipeline_TaskResult(a.(*TaskResult), b.(*pipeline.TaskResult), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*pipeline.TaskResult)(nil), (*TaskResult)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_pipeline_TaskResult_To_v1_TaskResult(a.(*pipeline.TaskResult), b.(*TaskResult), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TaskRunResult)(nil), (*pipeline.TaskRunResult)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_TaskRunResult_To_pipeline_TaskRunResult(a.(*TaskRunResult), b.(*pipeline.TaskRunResult), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*pipeline.TaskRunResult)(nil), (*TaskRunResult)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_pipeline_TaskRunResult_To_v1_TaskRunResult(a.(*pipeline.TaskRunResult), b.(*TaskRunResult), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TaskSpec)(nil), (*pipeline.TaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_TaskSpec_To_pipeline_TaskSpec(a.(*TaskSpec), b.(*pipeline.TaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*pipeline.TaskSpec)(nil), (*TaskSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_pipeline_TaskSpec_To_v1_TaskSpec(a.(*pipeline.TaskSpec), b.(*TaskSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkspaceBinding)(nil), (*pipeline.WorkspaceBinding)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_WorkspaceBinding_To_pipeline_WorkspaceBinding(a.(*WorkspaceBinding), b.(*pipeline.WorkspaceBinding), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*pipeline.WorkspaceBinding)(nil), (*WorkspaceBinding)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_pipeline_WorkspaceBinding_To_v1_WorkspaceBinding(a.(*pipeline.WorkspaceBinding), b.(*WorkspaceBinding), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkspaceDeclaration)(nil), (*pipeline.WorkspaceDeclaration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_WorkspaceDeclaration_To_pipeline_WorkspaceDeclaration(a.(*WorkspaceDeclaration), b.(*pipeline.WorkspaceDeclaration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*pipeline.WorkspaceDeclaration)(nil), (*WorkspaceDeclaration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_pipeline_WorkspaceDeclaration_To_v1_WorkspaceDeclaration(a.(*pipeline.WorkspaceDeclaration), b.(*WorkspaceDeclaration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkspacePipelineTaskBinding)(nil), (*pipeline.WorkspacePipelineTaskBinding)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_WorkspacePipelineTaskBinding_To_pipeline_WorkspacePipelineTaskBinding(a.(*WorkspacePipelineTaskBinding), b.(*pipeline.WorkspacePipelineTaskBinding), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*pipeline.WorkspacePipelineTaskBinding)(nil), (*WorkspacePipelineTaskBinding)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_pipeline_WorkspacePipelineTaskBinding_To_v1_WorkspacePipelineTaskBinding(a.(*pipeline.WorkspacePipelineTaskBinding), b.(*WorkspacePipelineTaskBinding), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkspaceUsage)(nil), (*pipeline.WorkspaceUsage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_WorkspaceUsage_To_pipeline_WorkspaceUsage(a.(*WorkspaceUsage), b.(*pipeline.WorkspaceUsage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*pipeline.WorkspaceUsage)(nil), (*WorkspaceUsage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_pipeline_WorkspaceUsage_To_v1_WorkspaceUsage(a.(*pipeline.WorkspaceUsage), b.(*WorkspaceUsage), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_Param_To_pipeline_Param(in *Param, out *pipeline.Param, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_v1_ParamValue_To_pipeline_ParamValue(&in.Value, &out.Value, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Param_To_pipeline_Param is an autogenerated conversion function.
func Convert_v1_Param_To_pipeline_Param(in *Param, out *pipeline.Param, s conversion.Scope) error {
	return autoConvert_v1_Param_To_pipeline_Param(in, out, s)
}

func autoConvert_pipeline_Param_To_v1_Param(in *pipeline.Param, out *Param, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_pipeline_ParamValue_To_v1_ParamValue(&in.Value, &out.Value, s); err != nil {
		return err
	}
	return nil
}

// Convert_pipeline_Param_To_v1_Param is an autogenerated conversion function.
func Convert_pipeline_Param_To_v1_Param(in *pipeline.Param, out *Param, s conversion.Scope) error {
	return autoConvert_pipeline_Param_To_v1_Param(in, out, s)
}

func autoConvert_v1_ParamSpec_To_pipeline_ParamSpec(in *ParamSpec, out *pipeline.ParamSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Type = pipeline.ParamType(in.Type)
	out.Description = in.Description
	out.Properties = *(*map[string]pipeline.PropertySpec)(unsafe.Pointer(&in.Properties))
	out.Default = (*pipeline.ParamValue)(unsafe.Pointer(in.Default))
	return nil
}

// Convert_v1_ParamSpec_To_pipeline_ParamSpec is an autogenerated conversion function.
func Convert_v1_ParamSpec_To_pipeline_ParamSpec(in *ParamSpec, out *pipeline.ParamSpec, s conversion.Scope) error {
	return autoConvert_v1_ParamSpec_To_pipeline_ParamSpec(in, out, s)
}

func autoConvert_pipeline_ParamSpec_To_v1_ParamSpec(in *pipeline.ParamSpec, out *ParamSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Type = ParamType(in.Type)
	out.Description = in.Description
	out.Properties = *(*map[string]PropertySpec)(unsafe.Pointer(&in.Properties))
	out.Default = (*ParamValue)(unsafe.Pointer(in.Default))
	return nil
}

// Convert_pipeline_ParamSpec_To_v1_ParamSpec is an autogenerated conversion function.
func Convert_pipeline_ParamSpec_To_v1_ParamSpec(in *pipeline.ParamSpec, out *ParamSpec, s conversion.Scope) error {
	return autoConvert_pipeline_ParamSpec_To_v1_ParamSpec(in, out, s)
}

func autoConvert_v1_ParamValue_To_pipeline_ParamValue(in *ParamValue, out *pipeline.ParamValue, s conversion.Scope) error {
	out.Type = pipeline.ParamType(in.Type)
	out.StringVal = in.StringVal
	out.ArrayVal = *(*[]string)(unsafe.Pointer(&in.ArrayVal))
	out.ObjectVal = *(*map[string]string)(unsafe.Pointer(&in.ObjectVal))
	return nil
}

// Convert_v1_ParamValue_To_pipeline_ParamValue is an autogenerated conversion function.
func Convert_v1_ParamValue_To_pipeline_ParamValue(in *ParamValue, out *pipeline.ParamValue, s conversion.Scope) error {
	return autoConvert_v1_ParamValue_To_pipeline_ParamValue(in, out, s)
}

func autoConvert_pipeline_ParamValue_To_v1_ParamValue(in *pipeline.ParamValue, out *ParamValue, s conversion.Scope) error {
	out.Type = ParamType(in.Type)
	out.StringVal = in.StringVal
	out.ArrayVal = *(*[]string)(unsafe.Pointer(&in.ArrayVal))
	out.ObjectVal = *(*map[string]string)(unsafe.Pointer(&in.ObjectVal))
	return nil
}

// Convert_pipeline_ParamValue_To_v1_ParamValue is an autogenerated conversion function.
func Convert_pipeline_ParamValue_To_v1_ParamValue(in *pipeline.ParamValue, out *ParamValue, s conversion.Scope) error {
	return autoConvert_pipeline_ParamValue_To_v1_ParamValue(in, out, s)
}

func autoConvert_v1_PipelineWorkspaceDeclaration_To_pipeline_PipelineWorkspaceDeclaration(in *PipelineWorkspaceDeclaration, out *pipeline.PipelineWorkspaceDeclaration, s conversion.Scope) error {
	out.Name = in.Name
	out.Description = in.Description
	out.Optional = in.Optional
	return nil
}

// Convert_v1_PipelineWorkspaceDeclaration_To_pipeline_PipelineWorkspaceDeclaration is an autogenerated conversion function.
func Convert_v1_PipelineWorkspaceDeclaration_To_pipeline_PipelineWorkspaceDeclaration(in *PipelineWorkspaceDeclaration, out *pipeline.PipelineWorkspaceDeclaration, s conversion.Scope) error {
	return autoConvert_v1_PipelineWorkspaceDeclaration_To_pipeline_PipelineWorkspaceDeclaration(in, out, s)
}

func autoConvert_pipeline_PipelineWorkspaceDeclaration_To_v1_PipelineWorkspaceDeclaration(in *pipeline.PipelineWorkspaceDeclaration, out *PipelineWorkspaceDeclaration, s conversion.Scope) error {
	out.Name = in.Name
	out.Description = in.Description
	out.Optional = in.Optional
	return nil
}

// Convert_pipeline_PipelineWorkspaceDeclaration_To_v1_PipelineWorkspaceDeclaration is an autogenerated conversion function.
func Convert_pipeline_PipelineWorkspaceDeclaration_To_v1_PipelineWorkspaceDeclaration(in *pipeline.PipelineWorkspaceDeclaration, out *PipelineWorkspaceDeclaration, s conversion.Scope) error {
	return autoConvert_pipeline_PipelineWorkspaceDeclaration_To_v1_PipelineWorkspaceDeclaration(in, out, s)
}

func autoConvert_v1_PropertySpec_To_pipeline_PropertySpec(in *PropertySpec, out *pipeline.PropertySpec, s conversion.Scope) error {
	out.Type = pipeline.ParamType(in.Type)
	return nil
}

// Convert_v1_PropertySpec_To_pipeline_PropertySpec is an autogenerated conversion function.
func Convert_v1_PropertySpec_To_pipeline_PropertySpec(in *PropertySpec, out *pipeline.PropertySpec, s conversion.Scope) error {
	return autoConvert_v1_PropertySpec_To_pipeline_PropertySpec(in, out, s)
}

func autoConvert_pipeline_PropertySpec_To_v1_PropertySpec(in *pipeline.PropertySpec, out *PropertySpec, s conversion.Scope) error {
	out.Type = ParamType(in.Type)
	return nil
}

// Convert_pipeline_PropertySpec_To_v1_PropertySpec is an autogenerated conversion function.
func Convert_pipeline_PropertySpec_To_v1_PropertySpec(in *pipeline.PropertySpec, out *PropertySpec, s conversion.Scope) error {
	return autoConvert_pipeline_PropertySpec_To_v1_PropertySpec(in, out, s)
}

func autoConvert_v1_Sidecar_To_pipeline_Sidecar(in *Sidecar, out *pipeline.Sidecar, s conversion.Scope) error {
	out.Name = in.Name
	out.Image = in.Image
	out.Command = *(*[]string)(unsafe.Pointer(&in.Command))
	out.Args = *(*[]string)(unsafe.Pointer(&in.Args))
	out.WorkingDir = in.WorkingDir
	out.Ports = *(*[]corev1.ContainerPort)(unsafe.Pointer(&in.Ports))
	out.EnvFrom = *(*[]corev1.EnvFromSource)(unsafe.Pointer(&in.EnvFrom))
	out.Env = *(*[]corev1.EnvVar)(unsafe.Pointer(&in.Env))
	out.ComputeResources = in.ComputeResources
	out.VolumeMounts = *(*[]corev1.VolumeMount)(unsafe.Pointer(&in.VolumeMounts))
	out.VolumeDevices = *(*[]corev1.VolumeDevice)(unsafe.Pointer(&in.VolumeDevices))
	out.LivenessProbe = (*corev1.Probe)(unsafe.Pointer(in.LivenessProbe))
	out.ReadinessProbe = (*corev1.Probe)(unsafe.Pointer(in.ReadinessProbe))
	out.StartupProbe = (*corev1.Probe)(unsafe.Pointer(in.StartupProbe))
	out.Lifecycle = (*corev1.Lifecycle)(unsafe.Pointer(in.Lifecycle))
	out.TerminationMessagePath = in.TerminationMessagePath
	out.TerminationMessagePolicy = corev1.TerminationMessagePolicy(in.TerminationMessagePolicy)
	out.ImagePullPolicy = corev1.PullPolicy(in.ImagePullPolicy)
	out.SecurityContext = (*corev1.SecurityContext)(unsafe.Pointer(in.SecurityContext))
	out.Stdin = in.Stdin
	out.StdinOnce = in.StdinOnce
	out.TTY = in.TTY
	out.Script = in.Script
	out.Workspaces = *(*[]pipeline.WorkspaceUsage)(unsafe.Pointer(&in.Workspaces))
	return nil
}

// Convert_v1_Sidecar_To_pipeline_Sidecar is an autogenerated conversion function.
func Convert_v1_Sidecar_To_pipeline_Sidecar(in *Sidecar, out *pipeline.Sidecar, s conversion.Scope) error {
	return autoConvert_v1_Sidecar_To_pipeline_Sidecar(in, out, s)
}

func autoConvert_pipeline_Sidecar_To_v1_Sidecar(in *pipeline.Sidecar, out *Sidecar, s conversion.Scope) error {
	out.Name = in.Name
	out.Image = in.Image
	out.Command = *(*[]string)(unsafe.Pointer(&in.Command))
	out.Args = *(*[]string)(unsafe.Pointer(&in.Args))
	out.WorkingDir = in.WorkingDir
	out.Ports = *(*[]corev1.ContainerPort)(unsafe.Pointer(&in.Ports))
	out.EnvFrom = *(*[]corev1.EnvFromSource)(unsafe.Pointer(&in.EnvFrom))
	out.Env = *(*[]corev1.EnvVar)(unsafe.Pointer(&in.Env))
	out.ComputeResources = in.ComputeResources
	out.VolumeMounts = *(*[]corev1.VolumeMount)(unsafe.Pointer(&in.VolumeMounts))
	out.VolumeDevices = *(*[]corev1.VolumeDevice)(unsafe.Pointer(&in.VolumeDevices))
	out.LivenessProbe = (*corev1.Probe)(unsafe.Pointer(in.LivenessProbe))
	out.ReadinessProbe = (*corev1.Probe)(unsafe.Pointer(in.ReadinessProbe))
	out.StartupProbe = (*corev1.Probe)(unsafe.Pointer(in.StartupProbe))
	out.Lifecycle = (*corev1.Lifecycle)(unsafe.Pointer(in.Lifecycle))
	out.TerminationMessagePath = in.TerminationMessagePath
	out.TerminationMessagePolicy = corev1.TerminationMessagePolicy(in.TerminationMessagePolicy)
	out.ImagePullPolicy = corev1.PullPolicy(in.ImagePullPolicy)
	out.SecurityContext = (*corev1.SecurityContext)(unsafe.Pointer(in.SecurityContext))
	out.Stdin = in.Stdin
	out.StdinOnce = in.StdinOnce
	out.TTY = in.TTY
	out.Script = in.Script
	out.Workspaces = *(*[]WorkspaceUsage)(unsafe.Pointer(&in.Workspaces))
	return nil
}

// Convert_pipeline_Sidecar_To_v1_Sidecar is an autogenerated conversion function.
func Convert_pipeline_Sidecar_To_v1_Sidecar(in *pipeline.Sidecar, out *Sidecar, s conversion.Scope) error {
	return autoConvert_pipeline_Sidecar_To_v1_Sidecar(in, out, s)
}

func autoConvert_v1_Step_To_pipeline_Step(in *Step, out *pipeline.Step, s conversion.Scope) error {
	out.Name = in.Name
	out.Image = in.Image
	out.Command = *(*[]string)(unsafe.Pointer(&in.Command))
	out.Args = *(*[]string)(unsafe.Pointer(&in.Args))
	out.WorkingDir = in.WorkingDir
	out.EnvFrom = *(*[]corev1.EnvFromSource)(unsafe.Pointer(&in.EnvFrom))
	out.Env = *(*[]corev1.EnvVar)(unsafe.Pointer(&in.Env))
	out.ComputeResources = in.ComputeResources
	out.VolumeMounts = *(*[]corev1.VolumeMount)(unsafe.Pointer(&in.VolumeMounts))
	out.VolumeDevices = *(*[]corev1.VolumeDevice)(unsafe.Pointer(&in.VolumeDevices))
	out.ImagePullPolicy = corev1.PullPolicy(in.ImagePullPolicy)
	out.SecurityContext = (*corev1.SecurityContext)(unsafe.Pointer(in.SecurityContext))
	out.Script = in.Script
	out.Timeout = (*metav1.Duration)(unsafe.Pointer(in.Timeout))
	out.Workspaces = *(*[]pipeline.WorkspaceUsage)(unsafe.Pointer(&in.Workspaces))
	out.OnError = pipeline.OnErrorType(in.OnError)
	out.StdoutConfig = (*pipeline.StepOutputConfig)(unsafe.Pointer(in.StdoutConfig))
	out.StderrConfig = (*pipeline.StepOutputConfig)(unsafe.Pointer(in.StderrConfig))
	return nil
}

// Convert_v1_Step_To_pipeline_Step is an autogenerated conversion function.
func Convert_v1_Step_To_pipeline_Step(in *Step, out *pipeline.Step, s conversion.Scope) error {
	return autoConvert_v1_Step_To_pipeline_Step(in, out, s)
}

func autoConvert_pipeline_Step_To_v1_Step(in *pipeline.Step, out *Step, s conversion.Scope) error {
	out.Name = in.Name
	out.Image = in.Image
	out.Command = *(*[]string)(unsafe.Pointer(&in.Command))
	out.Args = *(*[]string)(unsafe.Pointer(&in.Args))
	out.WorkingDir = in.WorkingDir
	out.EnvFrom = *(*[]corev1.EnvFromSource)(unsafe.Pointer(&in.EnvFrom))
	out.Env = *(*[]corev1.EnvVar)(unsafe.Pointer(&in.Env))
	out.ComputeResources = in.ComputeResources
	out.VolumeMounts = *(*[]corev1.VolumeMount)(unsafe.Pointer(&in.VolumeMounts))
	out.VolumeDevices = *(*[]corev1.VolumeDevice)(unsafe.Pointer(&in.VolumeDevices))
	out.ImagePullPolicy = corev1.PullPolicy(in.ImagePullPolicy)
	out.SecurityContext = (*corev1.SecurityContext)(unsafe.Pointer(in.SecurityContext))
	out.Script = in.Script
	out.Timeout = (*metav1.Duration)(unsafe.Pointer(in.Timeout))
	out.Workspaces = *(*[]WorkspaceUsage)(unsafe.Pointer(&in.Workspaces))
	out.OnError = OnErrorType(in.OnError)
	out.StdoutConfig = (*StepOutputConfig)(unsafe.Pointer(in.StdoutConfig))
	out.StderrConfig = (*StepOutputConfig)(unsafe.Pointer(in.StderrConfig))
	return nil
}

// Convert_pipeline_Step_To_v1_Step is an autogenerated conversion function.
func Convert_pipeline_Step_To_v1_Step(in *pipeline.Step, out *Step, s conversion.Scope) error {
	return autoConvert_pipeline_Step_To_v1_Step(in, out, s)
}

func autoConvert_v1_StepOutputConfig_To_pipeline_StepOutputConfig(in *StepOutputConfig, out *pipeline.StepOutputConfig, s conversion.Scope) error {
	out.Path = in.Path
	return nil
}

// Convert_v1_StepOutputConfig_To_pipeline_StepOutputConfig is an autogenerated conversion function.
func Convert_v1_StepOutputConfig_To_pipeline_StepOutputConfig(in *StepOutputConfig, out *pipeline.StepOutputConfig, s conversion.Scope) error {
	return autoConvert_v1_StepOutputConfig_To_pipeline_StepOutputConfig(in, out, s)
}

func autoConvert_pipeline_StepOutputConfig_To_v1_StepOutputConfig(in *pipeline.StepOutputConfig, out *StepOutputConfig, s conversion.Scope) error {
	out.Path = in.Path
	return nil
}

// Convert_pipeline_StepOutputConfig_To_v1_StepOutputConfig is an autogenerated conversion function.
func Convert_pipeline_StepOutputConfig_To_v1_StepOutputConfig(in *pipeline.StepOutputConfig, out *StepOutputConfig, s conversion.Scope) error {
	return autoConvert_pipeline_StepOutputConfig_To_v1_StepOutputConfig(in, out, s)
}

func autoConvert_v1_StepTemplate_To_pipeline_StepTemplate(in *StepTemplate, out *pipeline.StepTemplate, s conversion.Scope) error {
	out.Image = in.Image
	out.Command = *(*[]string)(unsafe.Pointer(&in.Command))
	out.Args = *(*[]string)(unsafe.Pointer(&in.Args))
	out.WorkingDir = in.WorkingDir
	out.EnvFrom = *(*[]corev1.EnvFromSource)(unsafe.Pointer(&in.EnvFrom))
	out.Env = *(*[]corev1.EnvVar)(unsafe.Pointer(&in.Env))
	out.ComputeResources = in.ComputeResources
	out.VolumeMounts = *(*[]corev1.VolumeMount)(unsafe.Pointer(&in.VolumeMounts))
	out.VolumeDevices = *(*[]corev1.VolumeDevice)(unsafe.Pointer(&in.VolumeDevices))
	out.ImagePullPolicy = corev1.PullPolicy(in.ImagePullPolicy)
	out.SecurityContext = (*corev1.SecurityContext)(unsafe.Pointer(in.SecurityContext))
	return nil
}

// Convert_v1_StepTemplate_To_pipeline_StepTemplate is an autogenerated conversion function.
func Convert_v1_StepTemplate_To_pipeline_StepTemplate(in *StepTemplate, out *pipeline.StepTemplate, s conversion.Scope) error {
	return autoConvert_v1_StepTemplate_To_pipeline_StepTemplate(in, out, s)
}

func autoConvert_pipeline_StepTemplate_To_v1_StepTemplate(in *pipeline.StepTemplate, out *StepTemplate, s conversion.Scope) error {
	out.Image = in.Image
	out.Command = *(*[]string)(unsafe.Pointer(&in.Command))
	out.Args = *(*[]string)(unsafe.Pointer(&in.Args))
	out.WorkingDir = in.WorkingDir
	out.EnvFrom = *(*[]corev1.EnvFromSource)(unsafe.Pointer(&in.EnvFrom))
	out.Env = *(*[]corev1.EnvVar)(unsafe.Pointer(&in.Env))
	out.ComputeResources = in.ComputeResources
	out.VolumeMounts = *(*[]corev1.VolumeMount)(unsafe.Pointer(&in.VolumeMounts))
	out.VolumeDevices = *(*[]corev1.VolumeDevice)(unsafe.Pointer(&in.VolumeDevices))
	out.ImagePullPolicy = corev1.PullPolicy(in.ImagePullPolicy)
	out.SecurityContext = (*corev1.SecurityContext)(unsafe.Pointer(in.SecurityContext))
	return nil
}

// Convert_pipeline_StepTemplate_To_v1_StepTemplate is an autogenerated conversion function.
func Convert_pipeline_StepTemplate_To_v1_StepTemplate(in *pipeline.StepTemplate, out *StepTemplate, s conversion.Scope) error {
	return autoConvert_pipeline_StepTemplate_To_v1_StepTemplate(in, out, s)
}

func autoConvert_v1_Task_To_pipeline_Task(in *Task, out *pipeline.Task, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_TaskSpec_To_pipeline_TaskSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Task_To_pipeline_Task is an autogenerated conversion function.
func Convert_v1_Task_To_pipeline_Task(in *Task, out *pipeline.Task, s conversion.Scope) error {
	return autoConvert_v1_Task_To_pipeline_Task(in, out, s)
}

func autoConvert_pipeline_Task_To_v1_Task(in *pipeline.Task, out *Task, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_pipeline_TaskSpec_To_v1_TaskSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_pipeline_Task_To_v1_Task is an autogenerated conversion function.
func Convert_pipeline_Task_To_v1_Task(in *pipeline.Task, out *Task, s conversion.Scope) error {
	return autoConvert_pipeline_Task_To_v1_Task(in, out, s)
}

func autoConvert_v1_TaskList_To_pipeline_TaskList(in *TaskList, out *pipeline.TaskList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]pipeline.Task)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_TaskList_To_pipeline_TaskList is an autogenerated conversion function.
func Convert_v1_TaskList_To_pipeline_TaskList(in *TaskList, out *pipeline.TaskList, s conversion.Scope) error {
	return autoConvert_v1_TaskList_To_pipeline_TaskList(in, out, s)
}

func autoConvert_pipeline_TaskList_To_v1_TaskList(in *pipeline.TaskList, out *TaskList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Task)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_pipeline_TaskList_To_v1_TaskList is an autogenerated conversion function.
func Convert_pipeline_TaskList_To_v1_TaskList(in *pipeline.TaskList, out *TaskList, s conversion.Scope) error {
	return autoConvert_pipeline_TaskList_To_v1_TaskList(in, out, s)
}

func autoConvert_v1_TaskResult_To_pipeline_TaskResult(in *TaskResult, out *pipeline.TaskResult, s conversion.Scope) error {
	out.Name = in.Name
	out.Type = pipeline.ResultsType(in.Type)
	out.Properties = *(*map[string]pipeline.PropertySpec)(unsafe.Pointer(&in.Properties))
	out.Description = in.Description
	return nil
}

// Convert_v1_TaskResult_To_pipeline_TaskResult is an autogenerated conversion function.
func Convert_v1_TaskResult_To_pipeline_TaskResult(in *TaskResult, out *pipeline.TaskResult, s conversion.Scope) error {
	return autoConvert_v1_TaskResult_To_pipeline_TaskResult(in, out, s)
}

func autoConvert_pipeline_TaskResult_To_v1_TaskResult(in *pipeline.TaskResult, out *TaskResult, s conversion.Scope) error {
	out.Name = in.Name
	out.Type = ResultsType(in.Type)
	out.Properties = *(*map[string]PropertySpec)(unsafe.Pointer(&in.Properties))
	out.Description = in.Description
	return nil
}

// Convert_pipeline_TaskResult_To_v1_TaskResult is an autogenerated conversion function.
func Convert_pipeline_TaskResult_To_v1_TaskResult(in *pipeline.TaskResult, out *TaskResult, s conversion.Scope) error {
	return autoConvert_pipeline_TaskResult_To_v1_TaskResult(in, out, s)
}

func autoConvert_v1_TaskRunResult_To_pipeline_TaskRunResult(in *TaskRunResult, out *pipeline.TaskRunResult, s conversion.Scope) error {
	out.Name = in.Name
	out.Type = pipeline.ResultsType(in.Type)
	if err := Convert_v1_ParamValue_To_pipeline_ParamValue(&in.Value, &out.Value, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_TaskRunResult_To_pipeline_TaskRunResult is an autogenerated conversion function.
func Convert_v1_TaskRunResult_To_pipeline_TaskRunResult(in *TaskRunResult, out *pipeline.TaskRunResult, s conversion.Scope) error {
	return autoConvert_v1_TaskRunResult_To_pipeline_TaskRunResult(in, out, s)
}

func autoConvert_pipeline_TaskRunResult_To_v1_TaskRunResult(in *pipeline.TaskRunResult, out *TaskRunResult, s conversion.Scope) error {
	out.Name = in.Name
	out.Type = ResultsType(in.Type)
	if err := Convert_pipeline_ParamValue_To_v1_ParamValue(&in.Value, &out.Value, s); err != nil {
		return err
	}
	return nil
}

// Convert_pipeline_TaskRunResult_To_v1_TaskRunResult is an autogenerated conversion function.
func Convert_pipeline_TaskRunResult_To_v1_TaskRunResult(in *pipeline.TaskRunResult, out *TaskRunResult, s conversion.Scope) error {
	return autoConvert_pipeline_TaskRunResult_To_v1_TaskRunResult(in, out, s)
}

func autoConvert_v1_TaskSpec_To_pipeline_TaskSpec(in *TaskSpec, out *pipeline.TaskSpec, s conversion.Scope) error {
	out.Params = *(*pipeline.ParamSpecs)(unsafe.Pointer(&in.Params))
	out.DisplayName = in.DisplayName
	out.Description = in.Description
	out.Steps = *(*[]pipeline.Step)(unsafe.Pointer(&in.Steps))
	out.Volumes = *(*[]corev1.Volume)(unsafe.Pointer(&in.Volumes))
	out.StepTemplate = (*pipeline.StepTemplate)(unsafe.Pointer(in.StepTemplate))
	out.Sidecars = *(*[]pipeline.Sidecar)(unsafe.Pointer(&in.Sidecars))
	out.Workspaces = *(*[]pipeline.WorkspaceDeclaration)(unsafe.Pointer(&in.Workspaces))
	out.Results = *(*[]pipeline.TaskResult)(unsafe.Pointer(&in.Results))
	return nil
}

// Convert_v1_TaskSpec_To_pipeline_TaskSpec is an autogenerated conversion function.
func Convert_v1_TaskSpec_To_pipeline_TaskSpec(in *TaskSpec, out *pipeline.TaskSpec, s conversion.Scope) error {
	return autoConvert_v1_TaskSpec_To_pipeline_TaskSpec(in, out, s)
}

func autoConvert_pipeline_TaskSpec_To_v1_TaskSpec(in *pipeline.TaskSpec, out *TaskSpec, s conversion.Scope) error {
	out.Params = *(*ParamSpecs)(unsafe.Pointer(&in.Params))
	out.DisplayName = in.DisplayName
	out.Description = in.Description
	out.Steps = *(*[]Step)(unsafe.Pointer(&in.Steps))
	out.Volumes = *(*[]corev1.Volume)(unsafe.Pointer(&in.Volumes))
	out.StepTemplate = (*StepTemplate)(unsafe.Pointer(in.StepTemplate))
	out.Sidecars = *(*[]Sidecar)(unsafe.Pointer(&in.Sidecars))
	out.Workspaces = *(*[]WorkspaceDeclaration)(unsafe.Pointer(&in.Workspaces))
	out.Results = *(*[]TaskResult)(unsafe.Pointer(&in.Results))
	return nil
}

// Convert_pipeline_TaskSpec_To_v1_TaskSpec is an autogenerated conversion function.
func Convert_pipeline_TaskSpec_To_v1_TaskSpec(in *pipeline.TaskSpec, out *TaskSpec, s conversion.Scope) error {
	return autoConvert_pipeline_TaskSpec_To_v1_TaskSpec(in, out, s)
}

func autoConvert_v1_WorkspaceBinding_To_pipeline_WorkspaceBinding(in *WorkspaceBinding, out *pipeline.WorkspaceBinding, s conversion.Scope) error {
	out.Name = in.Name
	out.SubPath = in.SubPath
	out.VolumeClaimTemplate = (*corev1.PersistentVolumeClaim)(unsafe.Pointer(in.VolumeClaimTemplate))
	out.PersistentVolumeClaim = (*corev1.PersistentVolumeClaimVolumeSource)(unsafe.Pointer(in.PersistentVolumeClaim))
	out.EmptyDir = (*corev1.EmptyDirVolumeSource)(unsafe.Pointer(in.EmptyDir))
	out.ConfigMap = (*corev1.ConfigMapVolumeSource)(unsafe.Pointer(in.ConfigMap))
	out.Secret = (*corev1.SecretVolumeSource)(unsafe.Pointer(in.Secret))
	out.Projected = (*corev1.ProjectedVolumeSource)(unsafe.Pointer(in.Projected))
	out.CSI = (*corev1.CSIVolumeSource)(unsafe.Pointer(in.CSI))
	return nil
}

// Convert_v1_WorkspaceBinding_To_pipeline_WorkspaceBinding is an autogenerated conversion function.
func Convert_v1_WorkspaceBinding_To_pipeline_WorkspaceBinding(in *WorkspaceBinding, out *pipeline.WorkspaceBinding, s conversion.Scope) error {
	return autoConvert_v1_WorkspaceBinding_To_pipeline_WorkspaceBinding(in, out, s)
}

func autoConvert_pipeline_WorkspaceBinding_To_v1_WorkspaceBinding(in *pipeline.WorkspaceBinding, out *WorkspaceBinding, s conversion.Scope) error {
	out.Name = in.Name
	out.SubPath = in.SubPath
	out.VolumeClaimTemplate = (*corev1.PersistentVolumeClaim)(unsafe.Pointer(in.VolumeClaimTemplate))
	out.PersistentVolumeClaim = (*corev1.PersistentVolumeClaimVolumeSource)(unsafe.Pointer(in.PersistentVolumeClaim))
	out.EmptyDir = (*corev1.EmptyDirVolumeSource)(unsafe.Pointer(in.EmptyDir))
	out.ConfigMap = (*corev1.ConfigMapVolumeSource)(unsafe.Pointer(in.ConfigMap))
	out.Secret = (*corev1.SecretVolumeSource)(unsafe.Pointer(in.Secret))
	out.Projected = (*corev1.ProjectedVolumeSource)(unsafe.Pointer(in.Projected))
	out.CSI = (*corev1.CSIVolumeSource)(unsafe.Pointer(in.CSI))
	return nil
}

// Convert_pipeline_WorkspaceBinding_To_v1_WorkspaceBinding is an autogenerated conversion function.
func Convert_pipeline_WorkspaceBinding_To_v1_WorkspaceBinding(in *pipeline.WorkspaceBinding, out *WorkspaceBinding, s conversion.Scope) error {
	return autoConvert_pipeline_WorkspaceBinding_To_v1_WorkspaceBinding(in, out, s)
}

func autoConvert_v1_WorkspaceDeclaration_To_pipeline_WorkspaceDeclaration(in *WorkspaceDeclaration, out *pipeline.WorkspaceDeclaration, s conversion.Scope) error {
	out.Name = in.Name
	out.Description = in.Description
	out.MountPath = in.MountPath
	out.ReadOnly = in.ReadOnly
	out.Optional = in.Optional
	return nil
}

// Convert_v1_WorkspaceDeclaration_To_pipeline_WorkspaceDeclaration is an autogenerated conversion function.
func Convert_v1_WorkspaceDeclaration_To_pipeline_WorkspaceDeclaration(in *WorkspaceDeclaration, out *pipeline.WorkspaceDeclaration, s conversion.Scope) error {
	return autoConvert_v1_WorkspaceDeclaration_To_pipeline_WorkspaceDeclaration(in, out, s)
}

func autoConvert_pipeline_WorkspaceDeclaration_To_v1_WorkspaceDeclaration(in *pipeline.WorkspaceDeclaration, out *WorkspaceDeclaration, s conversion.Scope) error {
	out.Name = in.Name
	out.Description = in.Description
	out.MountPath = in.MountPath
	out.ReadOnly = in.ReadOnly
	out.Optional = in.Optional
	return nil
}

// Convert_pipeline_WorkspaceDeclaration_To_v1_WorkspaceDeclaration is an autogenerated conversion function.
func Convert_pipeline_WorkspaceDeclaration_To_v1_WorkspaceDeclaration(in *pipeline.WorkspaceDeclaration, out *WorkspaceDeclaration, s conversion.Scope) error {
	return autoConvert_pipeline_WorkspaceDeclaration_To_v1_WorkspaceDeclaration(in, out, s)
}

func autoConvert_v1_WorkspacePipelineTaskBinding_To_pipeline_WorkspacePipelineTaskBinding(in *WorkspacePipelineTaskBinding, out *pipeline.WorkspacePipelineTaskBinding, s conversion.Scope) error {
	out.Name = in.Name
	out.Workspace = in.Workspace
	out.SubPath = in.SubPath
	return nil
}

// Convert_v1_WorkspacePipelineTaskBinding_To_pipeline_WorkspacePipelineTaskBinding is an autogenerated conversion function.
func Convert_v1_WorkspacePipelineTaskBinding_To_pipeline_WorkspacePipelineTaskBinding(in *WorkspacePipelineTaskBinding, out *pipeline.WorkspacePipelineTaskBinding, s conversion.Scope) error {
	return autoConvert_v1_WorkspacePipelineTaskBinding_To_pipeline_WorkspacePipelineTaskBinding(in, out, s)
}

func autoConvert_pipeline_WorkspacePipelineTaskBinding_To_v1_WorkspacePipelineTaskBinding(in *pipeline.WorkspacePipelineTaskBinding, out *WorkspacePipelineTaskBinding, s conversion.Scope) error {
	out.Name = in.Name
	out.Workspace = in.Workspace
	out.SubPath = in.SubPath
	return nil
}

// Convert_pipeline_WorkspacePipelineTaskBinding_To_v1_WorkspacePipelineTaskBinding is an autogenerated conversion function.
func Convert_pipeline_WorkspacePipelineTaskBinding_To_v1_WorkspacePipelineTaskBinding(in *pipeline.WorkspacePipelineTaskBinding, out *WorkspacePipelineTaskBinding, s conversion.Scope) error {
	return autoConvert_pipeline_WorkspacePipelineTaskBinding_To_v1_WorkspacePipelineTaskBinding(in, out, s)
}

func autoConvert_v1_WorkspaceUsage_To_pipeline_WorkspaceUsage(in *WorkspaceUsage, out *pipeline.WorkspaceUsage, s conversion.Scope) error {
	out.Name = in.Name
	out.MountPath = in.MountPath
	return nil
}

// Convert_v1_WorkspaceUsage_To_pipeline_WorkspaceUsage is an autogenerated conversion function.
func Convert_v1_WorkspaceUsage_To_pipeline_WorkspaceUsage(in *WorkspaceUsage, out *pipeline.WorkspaceUsage, s conversion.Scope) error {
	return autoConvert_v1_WorkspaceUsage_To_pipeline_WorkspaceUsage(in, out, s)
}

func autoConvert_pipeline_WorkspaceUsage_To_v1_WorkspaceUsage(in *pipeline.WorkspaceUsage, out *WorkspaceUsage, s conversion.Scope) error {
	out.Name = in.Name
	out.MountPath = in.MountPath
	return nil
}

// Convert_pipeline_WorkspaceUsage_To_v1_WorkspaceUsage is an autogenerated conversion function.
func Convert_pipeline_WorkspaceUsage_To_v1_WorkspaceUsage(in *pipeline.WorkspaceUsage, out *WorkspaceUsage, s conversion.Scope) error {
	return autoConvert_pipeline_WorkspaceUsage_To_v1_WorkspaceUsage(in, out, s)
}
