apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: "admin" # required field for kubernetes.io/basic-auth
  password: "t0p-Secret" # required field for kubernetes.io/basic-auth
---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: secret-env-from
spec:
  taskSpec:
    steps:
    - name: secret-env-from
      image: mirror.gcr.io/ubuntu
      script: |
        #!/usr/bin/env bash
        echo "username env variable = $username"
        echo "password env variable = $password"
        BASIC_AUTH=$(echo -n "$username:$password" | base64)
        echo  $(echo -n "$BASIC_AUTH" | base64 -d) when base64 encoded becomes "$BASIC_AUTH"
        echo "Example Authorization header..."
        echo "Authorization: Basic $BASIC_AUTH"

      envFrom:
        - secretRef:
            name: secret-basic-auth
