name: Tekton Extra end-to-end tests

on:
  repository_dispatch:
    types: [e2e-extras-command]

permissions:
  contents: read
  pull-requests: read

defaults:
  run:
    shell: bash

jobs:
  run-if-requested:
    runs-on: ubuntu-latest
    steps:
    - name: Show Github Object
      run: |
        cat <<'EOF'
        ${GITHUB_CONTEXT}
        EOF
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
    - name: Show Github Event Path Json
      run: 'cat $GITHUB_EVENT_PATH || true'
    - name: Set PR variables
      id: pr
      uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
      env:
        ISSUE_NUMBER: ${{ github.event.client_payload.github.payload.issue.number }}
      with:
        script: |
          const pr = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: parseInt(process.env.ISSUE_NUMBER, 10)
          });
          core.setOutput('sha', pr.data.head.sha);

    - name: Create comment
      if: ${{ failure() }}
      run: |
        gh issue comment "${ISSUE_NUMBER}" \
          --repo "${REPO}" \
          --body "Something went wrong with your \`/${COMMAND}\` command: [please check the logs](${RUN_URL})."
      env:
        GH_TOKEN: ${{ secrets.CHATOPS_TOKEN }}
        REPO: ${{ github.event.client_payload.github.payload.repository.full_name }}
        ISSUE_NUMBER: ${{ github.event.client_payload.github.payload.issue.number }}
        COMMAND: ${{ github.event.client_payload.slash_command.command }}
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

    - name: Add reaction
      if: ${{ success() }}
      run: |
        gh api "repos/${REPO}/issues/comments/${COMMENT_ID}/reactions" \
          -f content='hooray'
      env:
        GH_TOKEN: ${{ secrets.CHATOPS_TOKEN }}
        REPO: ${{ github.event.client_payload.github.payload.repository.full_name }}
        COMMENT_ID: ${{ github.event.client_payload.github.payload.comment.id }}
    outputs:
      sha: ${{ steps.pr.outputs.sha }}

  e2e-extras:
    needs: [run-if-requested]
    permissions:
      contents: read
      checks: write # Used to create/update check runs
    if: ${{ needs.run-if-requested.result == 'success' }}
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.os }}-${{ matrix.k8s-name }}-${{ matrix.feature-flags }}-${{ github.event.client_payload.github.payload.issue.number }}
      cancel-in-progress: true
    name: e2e tests (extras)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        k8s-name:
        - k8s-latest-minus-five  # 1.29
        - k8s-latest-minus-four  # 1.30
        - k8s-latest-minus-three # 1.31
        - k8s-latest-minus-two   # 1.32
        - k8s-latest-minus-one   # 1.33
        feature-flags: [stable]
        include:
        - k8s-name: k8s-latest-minus-five
          k8s-version: v1.29.x
        - k8s-name: k8s-latest-minus-four
          k8s-version: v1.30.x
        - k8s-name: k8s-latest-minus-three
          k8s-version: v1.31.x
        - k8s-name: k8s-latest-minus-two
          k8s-version: v1.32.x
        - k8s-name: k8s-latest-minus-one
          k8s-version: v1.33.x
    env:
      KO_DOCKER_REPO: registry.local:5000/tekton
      CLUSTER_DOMAIN: c${{ github.run_id }}.local
      ARTIFACTS: ${{ github.workspace }}/artifacts
      KOCACHE: /tmp/ko-cache
    steps:
    - name: Report tests check
      uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
      id: check-run
      env:
        HEAD_SHA: ${{ needs.run-if-requested.outputs.sha }}
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const check = await github.rest.checks.create({
            name: 'run tests',
            head_sha: process.env.HEAD_SHA,
            status: 'in_progress',
            details_url: process.env.RUN_URL,
            ...context.repo
          })
          return { id: check.data.id }

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      with:
        ref: ${{ needs.run-if-requested.outputs.sha }}
        persist-credentials: false
    - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417  # v6.3.0
      with:
        go-version-file: "go.mod"
    - name: Cache ko build cache
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae  # v5.0.5
      with:
        path: /tmp/ko-cache
        key: ${{ runner.os }}-${{ runner.arch }}-ko-${{ hashFiles('go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-ko-
    - uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d # v0.9

    - name: Install Dependencies
      run: |
        echo '::group:: install go-junit-report'
        go install github.com/jstemmer/go-junit-report@v0.9.1
        echo '::endgroup::'
        echo '::group:: created required folders'
        mkdir -p "${ARTIFACTS}"
        echo '::endgroup::'
        echo "${GOPATH}/bin" >> "$GITHUB_PATH"

    - name: Run tests
      run: |
        export PATH="$(echo "$PATH" | sed -e 's/^\/bin://'):/bin"
        export KO_DEFAULTPLATFORMS=linux/$(go env GOARCH)
        ./hack/setup-kind.sh \
          --registry-url $(echo ${KO_DOCKER_REPO} | cut -d'/' -f 1) \
          --cluster-suffix c${{ github.run_id }}.local \
          --nodes 3 \
          --k8s-version ${{ matrix.k8s-version }} \
          --e2e-script ./test/e2e-tests.sh \
          --e2e-env ./test/e2e-tests-kind-${{ matrix.feature-flags }}.env

    - name: Upload test results
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: extra-tests-${{ matrix.k8s-version }}-${{ matrix.feature-flags }}-${{ matrix.os }}
        path: ${{ env.ARTIFACTS }}

    - uses: chainguard-dev/actions/kind-diag@de68b87302e6266db5fb5220246f8aa46fe94b67 # v1.6.14
      if: ${{ failure() }}
      with:
        artifact-name: extra-tests-${{ matrix.k8s-version }}-${{ matrix.feature-flags }}-${{ matrix.os }}-logs

    - name: Report tests check
      if: success() || failure()
      uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
      env:
        CHECK_RUN_ID: ${{ fromJSON(steps.check-run.outputs.result).id }}
        HEAD_SHA: ${{ needs.run-if-requested.outputs.sha }}
        TEST_OUTCOME: ${{ steps.tests-step.outcome }}
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const resp = await github.rest.checks.update({
            name: 'run tests',
            check_run_id: parseInt(process.env.CHECK_RUN_ID, 10),
            head_sha: process.env.HEAD_SHA,
            status: 'completed',
            conclusion: process.env.TEST_OUTCOME,
            details_url: process.env.RUN_URL,
            output: {
              title: 'Run tests',
              summary: `Results: ${process.env.TEST_OUTCOME}\n\n${process.env.RUN_URL}`
            },
            ...context.repo
          })
          console.log(`Check run create response: ${resp.status}`)
          console.log(`Check run URL: ${resp.data.url}`)
          console.log(`Check run HTML: ${resp.data.html_url}`)

    - name: Dump Artifacts
      if: ${{ failure() }}
      run: |
        if [[ -d ${ARTIFACTS} ]]; then
          cd ${ARTIFACTS}
          for x in $(find . -type f); do
            echo "::group:: artifact $x"
            cat $x
            echo '::endgroup::'
          done
        fi
