name: Go coverage

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  # run at least once every 2 months to prevent the coverage artifact from expiring
  schedule:
    - cron: '14 3 2 */2 *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  go-coverage:
    name: Go coverage
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: ${{ github.workspace }}/src/github.com/tektoncd/pipeline
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417  # v6.3.0
        with:
          go-version-file: "${{ github.workspace }}/src/github.com/tektoncd/pipeline/go.mod"

      - name: Generate coverage
        working-directory: ${{ github.workspace }}/src/github.com/tektoncd/pipeline
        run: |
          go test -cover -coverprofile=coverage.txt ./... || true
          echo "Generated coverage profile"

      - name: Archive coverage results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: code-coverage
          path: ${{ github.workspace }}/src/github.com/tektoncd/pipeline/coverage.txt

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: fgrosse/go-coverage-report@cbeb2ab2e32591d690337146ba02a911cc566f3f # v1.3.0
        continue-on-error: true # This may fail if artifact on main branch does not exist (first run or expired)
        env:
          GITHUB_TOKEN: ${{ secrets.CHATOPS_TOKEN }}
        with:
          coverage-artifact-name: "code-coverage"
          coverage-file-name: "coverage.txt"
