---
name: Label Checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:

  check_labels:
    name: Check kind labels
    runs-on: ubuntu-latest
    steps:
      - uses: agilepathway/label-checker@ca6a0a663cbcf80bb9c7a10d000d7b6a54495ce0 # v1.6.115
        with:
          prefix_mode: true
          one_of: "kind/"
          repo_token: ${{ secrets.GITHUB_TOKEN }}