---
name: Label Checker
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:

  check_labels:
    name: Check kind labels
    runs-on: ubuntu-latest
    steps:
      - uses: agilepathway/label-checker@3e994967b467ef4e4fddc82360ca60ef42b10120 # v1.6.98
        with:
          prefix_mode: true
          one_of: "kind/"
          repo_token: ${{ secrets.GITHUB_TOKEN }}